name: Publish Package to npmjs
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install deps
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Bump patch version
        if: "!contains(github.event.head_commit.message, 'chore: bump version')"
        run: |
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          npm version patch -m "chore: bump version to %s"
          git push
      - name: Publish to npm
        if: "!contains(github.event.head_commit.message, 'chore: bump version')"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}